apiVersion: v1
kind: Service
metadata:
  name: velocity-dev
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: proxy
    port: 25565
    targetPort: proxy
  selector:
    app: velocity-dev
