apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: velocity-dev
  name: velocity-dev
spec:
  selector:
    matchLabels:
      app: velocity-dev
  serviceName: velocity-dev
  template:
    metadata:
      labels:
        app: velocity-dev
    spec:
      serviceAccountName: velocity
      containers:
        - image: arturoguerra/velocity:dev
          imagePullPolicy: Always
          name: velocity-dev
          ports:
            - name: proxy
              containerPort: 25577
          env:
            - name: MAX_MEMORY
              value: 2G
            - name: PLUGINS
              value: https://arturo-minecraft-server-installers.nyc3.digitaloceanspaces.com/plugins.zip
          volumeMounts:
            - name: velocity-dev-data
              mountPath: /data
          resources:
            requests:
                cpu: 100m
                memory: 256Mi
            limits:
                cpu: "1"
                memory: 2Gi
  volumeClaimTemplates:
      - metadata:
          name: velocity-dev-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi