---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocity
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velocity-services-watcher-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velocity-services-watcher
subjects:
- kind: ServiceAccount
  name: velocity
  namespace: minecraft
roleRef:
  kind: ClusterRole
  name: velocity-services-watcher-role
  apiGroup: rbac.authorization.k8s.io
